services:
  postgres:
    image: postgres:16-alpine
    container_name: techstore-postgres
    environment:
      POSTGRES_DB: sales_app_db
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-12345}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: techstore-redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: techstore-springboot-app
    ports:
      - "8080:8080"
    environment:
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-12345}
      - JWT_SECRET=${JWT_SECRET}
      - VNP_TMNCODE=${VNP_TMNCODE}
      - VNP_HASHSECRET=${VNP_HASHSECRET}
      - PO_CLIENTID=${PO_CLIENTID}
      - PO_APIKEY=${PO_APIKEY}
      - PO_CHECKSUMKEY=${PO_CHECKSUMKEY}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sales_app_db
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data:
